/* global pywebview */

import * as React from 'react'

import './Ticker.sass'
import logo from '../../assets/logo.png'


export default function Ticker() {
  const [ticker, setTicker] = React.useState('')

  React.useEffect(() => {
    window.addEventListener('pywebviewready', function () {

      if (!(window as any).pywebview.state) {
        (window as any).pywebview.state = {}
      }
      // Expose setTicker in order to call it from Python
      (window as any).pywebview.state.setTicker = setTicker
    })
  }, [])

  return (
    <div className='ticker-container'>
      <h1>Welcome to pywebview <img className='logo' src={logo} alt='pywebview' /></h1>


      <em>You can freely communicate between Javascript with Python without an HTTP server. This value, for example, is being generated by Python code:</em>
      <strong>{ticker}</strong>
    </div>
  )
}
